export enum FaqStatus {
	ACTIVE = 'ACTIVE',
	BLOCKED = 'BLOCKED',
	DELETED = 'DELETED',
}

export enum FaqCategory {
	GENERAL = 'GENERAL',
	FOR_STUDENTS = 'FOR_STUDENTS',
	FOR_TEACHERS = 'FOR_TEACHERS',
	MEMBERSHIP = 'MEMBERSHIP',
	COMMUNITY = 'COMMUNITY',
	PAYMENT = 'PAYMENT',
	COURSE = 'COURSE',
	OTHERS = 'OTHERS',
}
